---
title: |
  | BIOF339: Practical R
  | Lectures
author: Abhijit Dasgupta
output:
  html_document:
    theme: cosmo
    highlight: textmate
    css: css/styles.css

---

```{r, include = FALSE, eval = knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"}
# Enables Font Awesome in HTML based bookdown outputs.
fa <- rmarkdown::html_dependency_font_awesome()
fa$attachment <- "fonts/fontawesome-webfont.ttf"
htmltools::tagList(fa)
knitr::opts_chunk$set(echo = FALSE)
```

### Contents

```{r top-table, echo = F, message=F, warning=F}
pacman::p_load(char = c('tidyverse','fs','glue','kableExtra','knitr','here', 'gt'))

parse_title <- function(f){
  if(is.na(f)) return(NA)
  rmarkdown::yaml_front_matter(f)$title
}
setwd(here::here('slides'))
rmdfiles <- dir_ls('.', regex='week\\d/\\d+.*Rmd', recurse = TRUE)

tbl <- tibble(Week = str_extract(rmdfiles, 'week\\d'), 
              'Source' = rmdfiles) %>% 
  mutate(Week = paste('Week', parse_number(Week)),
         Unit = parse_number(basename(Source)),
         Title = map_chr(rmdfiles, parse_title),
         Title = str_remove(Title, 'Practical R: ')) %>% 
  mutate(HTML = glue('[HTML]({str_replace(Source, "Rmd","html")})'))

pdffiles <- path('docs','slides',str_replace(rmdfiles, 'Rmd','pdf'))
pdf_exists <- file_exists(here(pdffiles))
pdf_urls <- glue("[PDF]({str_replace(rmdfiles, 'Rmd','pdf')})")
pdf_urls[!pdf_exists] <- ''
tbl <- tbl %>% 
  mutate(PDF = pdf_urls)

rmd_url_lead <- 'https://raw.githubusercontent.com/araastat/BIOF339/master/slides'
tbl <- tbl %>% 
  mutate(`R Markdown` = glue('[Rmd]({paste(rmd_url_lead, rmdfiles, sep="/")})'))

## Cleanup
tbl <- tbl %>% 
  mutate(Title = str_extract(Title, '[[:alpha:] ]+'))

# tbl %>% 
#   select(-Source) %>% 
#   kable() %>% 
#   kable_styling(full_width=FALSE)

tbl %>% 
  select(-Source) %>% 
  gt(
    rowname_col = 'Unit',
    groupname_col = 'Week'
  ) %>% 
  fmt_markdown(columns=TRUE) %>% 
  tab_header(title='Contents') %>% 
  tab_style(
    style = list(
      cell_text(align='right')
    ),
    locations = cells_body(
      columns = vars(HTML)
    )
  )
  
  

setwd(here())
```



## Dashboard example

See link [here](dashboard2.Rmd). You need to download and run locally since Shiny is being used
