---
title: "Reported Confirmed Malaria Cases and Deaths Worldwide from 2000-2017"
author: "Nadia Raytselis" 
abstract: "The following report contains two data sets from the World Health Organization (WHO). The datasets are titled: Reported indigenous confirmed cases Data by country AND Reported deaths Data by country."
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: columns 
#   runtime: shiny 
---

```{r setup, include=FALSE, warning=FALSE}
library(flexdashboard)
library(tidyverse)
# library(shiny)
```

```{r, warning=FALSE, include=FALSE}
library("rio")
malaria_cases <- import("malaria_cases.csv")

malaria_deaths <- import("malaria_deaths.csv")
```

```{r, warning=FALSE, include=FALSE}
colnames(malaria_cases) = malaria_cases[1, ] 
malaria_cases = malaria_cases[-1, ]   

colnames(malaria_deaths) = malaria_deaths[1, ] 
malaria_deaths = malaria_deaths[-1, ]   
```

```{r, warning=FALSE, include=FALSE}
malaria_cases_select <- tidyr::gather( malaria_cases, key = "Year", value = "Cases", c(2:19))
```

```{r, warning=FALSE, include=FALSE}
malaria_deaths_select <- tidyr::gather( malaria_deaths, key = "Year", value = "Deaths", c(2:19))
```


-----------------------------------------------------------------------

### Abstract

The following report contains two data sets from the World Health Organization (WHO). The datasets are titled: Reported indigenous confirmed cases Data by country AND Reported deaths Data by country.

### Chart A

```{r, warning=FALSE, echo=F}
malaria_cases_gg <- ggplot(
 data = malaria_cases_select,
 mapping = aes(
 x = Year,
 y = Cases
 )
) +
 geom_point() + ggtitle("Malaria - Reported Confirmed Cases from 2000-2017") 

malaria_cases_gg
```

### Chart B
```{r, message=F, warning=FALSE, echo=F}
library(plotly)
p <- plot_ly(malaria_cases_select, x = ~Year, y = ~Cases, text = ~Country, type = 'scatter', mode = 'markers', color = ~Country, colors = 'Paired',
        marker = list(opacity = 0.5, sizemode = 'diameter')) %>%
  layout(title = 'Malaria Cases Worldwide 2000-2017',
         xaxis = list(showgrid = FALSE),
         yaxis = list(showgrid = FALSE),
         showlegend = FALSE)
p
```

### Chart C
```{r, warning=FALSE, echo=F}
malaria_deaths_gg <- ggplot(
 data = malaria_deaths_select,
 mapping = aes(
 x = Year,
 y = Deaths
 )
) +
 geom_point () + ggtitle("Malaria - Reported Deaths from 2000-2017") 

malaria_deaths_gg
```



### Chart D
```{r, warning=FALSE, echo=F}
library(plotly)
p2 <- plot_ly(malaria_deaths_select, x = ~Year, y = ~Deaths, text = ~Country, type = 'scatter', mode = 'markers', color = ~Country, colors = 'Paired',
        marker = list(opacity = 0.5, sizemode = 'diameter')) %>%
  layout(title = 'Malaria Deaths Worldwide 2000-2017',
         xaxis = list(showgrid = FALSE),
         yaxis = list(showgrid = FALSE),
         showlegend = FALSE)
p2
```

### Chart E
```{r, echo=FALSE, message=F, warning=FALSE, echo=F, fig.width = 10, fig.height = 25}
library(ggplot2)
library(plotly)
library(gapminder)
 
p <- malaria_cases_select %>%
  ggplot(aes(Cases, Country, color=Year)) +
  geom_point() + ggtitle("Malaria - Reported Confirmed Cases from 2000-2017 by Country") +
  scale_x_log10() +
  theme_bw() 

ggplotly(p)
```

### Chart F
```{r, warning=FALSE, echo=F, fig.width = 10, fig.height = 25}
library(ggplot2)
library(plotly)
library(gapminder)
 
p <- malaria_deaths_select %>%
  ggplot(aes(Deaths, Country, color=Year)) +
  geom_point() + ggtitle("Malaria - Reported Deaths from 2000-2017 by Country") + scale_x_log10() +
  theme_bw() 

ggplotly(p)
``` 














