---
title: Assignments
author: BIOF 339
output:
  html_document:
    theme: cosmo
    highlight: textmate
    css: style.css
---

```{r, echo=FALSE}
fa <- rmarkdown::html_dependency_font_awesome()
fa$attachment <- "fonts/fontawesome-webfont.ttf"
htmltools::tagList(fa)
knitr::opts_chunk$set(echo = FALSE)
start_date <- '2021-08-30'
```


## Homeworks

```{r echo=F, message=FALSE}
library(tidyverse)
library(glue)
library(fs)
library(here)
library(gt)
setwd(here('assignments'))

pacman::p_load(tidyverse, fs, glue, kableExtra, knitr, here, gt,lubridate)
start_date <- as_date(start_date)
dts <- start_date + days(7* (0:6))
curr_date <- as_date(Sys.Date())
weeks <- data.frame("Week" = paste("Week", 1:6), "Start" = dts[1:6])

hwfiles <- tibble(url = as.character(dir_ls('.', regex = 'HW/week\\d/week\\d.Rmd' , recurse=TRUE))) %>% 
  mutate(Week = str_extract(url, 'week\\d'))
solutions <- tibble(sol_url = as.character(dir_ls('.', regex = 'HW/week\\d/week\\d_solution[s]*.Rmd', recurse=TRUE))) %>% 
  mutate(Week = str_extract(sol_url, 'week\\d'))
hwfiles <- hwfiles %>% left_join(solutions) %>% relocate(Week) %>% 
  mutate(Homework = glue("<a href='{str_replace(url, 'Rmd','html')}' target=
                         '_blank'>link</a>")) %>% 
  mutate(Solution = ifelse(is.na(sol_url),
                           '',
                           glue("<a href='{str_replace(sol_url, 'Rmd','html')}' target='_blank'>link</a>")))
```

```{r echo=F, message=FALSE}

out <- hwfiles %>% 
  mutate(Week = str_replace(Week, 'week(\\d)', 'Week \\1')) %>% 
  select(-contains('url')) %>% 
  right_join(weeks) %>% 
  filter(Start <= curr_date) %>% 
  mutate(Solution = ifelse(Start >= curr_date - days(7), '', Solution)) %>% 
  select(-Start)

gt(out) %>% 
  fmt_markdown(columns = TRUE)

setwd(here())
```
