---
title: "Data exploration"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    runtime: shiny
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
```

Column {.sidebar}
-------------------------------------------------------

```{r}
selectInput('xvar', label = 'X Variable',
            choices = names(iris)[-5])
selectInput('yvar', label = 'Y Variable',
            choices = names(iris)[-5],
            selected = names(iris)[[2]])


```


Row {data-height=400}
-----------------------------------------------------------------------

### Scatter

```{r}

selectedData <- reactive({
  iris[,c(input$xvar, input$yvar)]
})

renderPlot({
  ggplot(selectedData(), aes_string(
    x = input$xvar, 
    y = input$yvar
  )) + geom_point()
})
# ggplot(iris, aes(Sepal.Length, Sepal.Width))+
#   geom_point() + theme_dark()
```

Row {data-height=400}
-----------------------------------------------------------------------

### Boxplot

```{r}

selectedData2 <- reactive({
  iris[,c('Species',input$xvar)]
})

renderPlot({
  ggplot(selectedData2(), 
         aes_string(x = 'Species',y = input$xvar))+
    geom_boxplot()
})
# ggplot(iris, aes(Species, Sepal.Length))+
#   geom_boxplot()
```

