---
title: "BIOF 339: Practical R"
output:
  html_document:
    theme: cosmo
    highlight: textmate
    toc: false
---

## [Abhijit Dasgupta, PhD](https://webbedfeet.netlify.com){target=_blank}

Dr. Dasgupta is a biostatistician and data scientist with experience in
statistical modeling and machine learning, bioinformatics, optimization, signal
processing, and data visualization. He holds a PhD in Biostatistics with earlier
training in Mathematical Statistics. He has been using R for over 20 years for a
wide variety of applications in biomedical research, as well as for data-driven
reports and presentations. He co-founded and organized the [Statistical Programming
DC](http://www.meetup.com/stats-prog-dc) meetup (formerly R Users Group DC) and
served on the Board of [Data Community DC](http://www.datacommunitydc.org). He
regularly gives workshops and webinars on using R and Python for data analysis,
machine learning and visualization.

Dr. Dasgupta currently is  Data Science Associate Director at [AstraZeneca](https://www.astrazeneca.com). He previously served for 10+ years as a consultant to the [National Institute of Arthritis,
Musculoskeletal and Skin
Disorders](https://www.niams.nih.gov/about/directory/abhijit-dasgupta-phd){target=_blank},
part of the NIH, where he worked on complex analyses of healthcare databases as
well as outcomes research and bioinformatics. He also is Co-Founder and Chief Data Scientist at
[Zansors](http://www.zansors.com){target=_blank}, a healthcare wearable and
analytics company based in Arlington, Virginia. He maintains his clinical trial chops 
by serving as a reviewer on [NIMH](http://nimh.nih.gov) Data Safety Monitoring Boards.

Dr. Dasgupta is a certified
[Carpentries](http://www.carpentries.org){target=_blank} instructor, and, with
[District Data Labs](http://www.districtdatalabs.com){target=_blank}, he
provides high quality cirruculum development and training in data science
programming using R and Python.

Dr. Dasgupta and his wife have two teenage children and a golden retriever puppy named
Jingle. He is also a 4^th^ degree black belt in aikido, having practiced the martial
art for over 25 years. 

