---
title: "Homework 5: Plotting"
author: ""
date: "Due Wednesday October 16, 2019"
output: html_document
---

<p style="color: black; border:3px; border-style: solid; border-color: red;padding: 1em; background-color: wheat;font-size: 14pt;text-align:center">
[**Submission Link**](https://www.dropbox.com/request/MTY0A7xHdxVdwj1GTRBO){target=_blank}
</p>



## Reading

1. Please read [Chapter 3](https://r4ds.had.co.nz/data-visualisation.html#introduction-1) 
of R4DS. This is a really nice reference. If you're interested, look at [section 3.7](https://r4ds.had.co.nz/data-visualisation.html#statistical-transformations) for a deeper understanding of how different statistical transformations can be accommodated within different geometries in ggplot2. 

## Exercises

<ol>
<li> Let's look at the  [breast cancer data set](data/clinical_data_breast_cancer_hw.csv) we'be been using.  

<ol>
  <li> Create a bar plot of the frequencies of ER status (Hint: `geom_bar`. How would you modify the dataset
  so that there is no separate bar for NA's?
  <li> Color each bar by the frequencies of HER2 status within each group. (Hint: you can add `aes(color='HER2.Status')` or `aes(fill='HER2.Status')` to the `geom_bar` statement. What is the difference in these two choices?)
  <li> I would like to see a graph showing the relative frequencies of HER2 status within each ER group. Read the documentation `?geom_bar` as well as section 3.8 of R4DS to find this solution. 
</ol>

<li> The `diamonds` dataset is included in the `ggplot2` package. 
<ol>
<li> Add a column to the diamonds dataset that is the volume of each diamond (multiplying the `x`, `y` and `z` variables)
<li> Plot a scatter plot of diamond price against diamond volume
<li> Modify the plot to add colors based on the cut of each diamond
<li> Modify the previous plot to construct a facetted plot where each facet is based on a color.
</ol>
</ol>

### Extra credit

The [breast cancer expression](data/BreastCancer_Expression.xlsx) dataset contains 
log-expression levels of 10 probes for the same individuals that are in the clinical dataset.

1. Modify the dataset appropriately and draw a facetted plot where each facet is a histogram of the expression levels of each probe. 

